---
# handlers file for ansible-role-proxmox
- name: Restart pvedaemon
  ansible.builtin.service:
    name: pvedaemon
    state: restarted

- name: Restart pveproxy
  ansible.builtin.service:
    name: pveproxy
    state: restarted

- name: Reload ssh server configuration
  ansible.builtin.systemd_service:
    name: ssh.service
    state: reloaded

- name: Restart watchdog-mux
  ansible.builtin.service:
    name: watchdog-mux
    state: restarted

- name: Restart rrdcached
  ansible.builtin.systemd_service:
    name: rrdcached
    state: restarted

# PVE requires some exotic settings, as the PVE-kernel does not support boottime ansible-style
- name: Restart PVE machine
  ansible.builtin.reboot:
    post_reboot_delay: 45
    reboot_timeout: 90
    boot_time_command: "who -b"
